import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import { poppins } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen bg-zinc-200 flex flex-col`}>
        <header>
          <Navbar />
        </header>
        <main className="flex-grow flex w-full items-center flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
